### ISSUE TITLE
RuntimeError: Cannot return the results in a contiguous 2D array. Probably ef or M is too small

### ISSUE THREAD

**Issue by oliveiracwb** [circlemind-ai/fast-graphrag#22]
**Describe the bug**
RuntimeError: Cannot return the results in a contiguous 2D array. Probably ef or M is too small

**To Reproduce**
1. Simple document in UTF
2. Simple query:
´´
from fast_graphrag import GraphRAG

DOMAIN = "Quais os elementos envolvidos na história abaixo."

EXAMPLE_QUERIES = [
    "Quais são os personagens, elementos e datas envolvidas e como elas se relacionam ?"
]

ENTITY_TYPES = ["Pessoas", "Lugares", "Datas"]

grag = GraphRAG(
    working_dir="./book_example",
    domain=DOMAIN,
    example_queries="\n".join(EXAMPLE_QUERIES),
    entity_types=ENTITY_TYPES
)

with open("./book.txt") as f:
    grag.insert(f.read())

print(grag.query("Quais os elementos envolvidos?").response)
´´

**Comment by liukidar** [comment]
This should have been fixed with the last commit, please try!

**Comment by liukidar** [comment]
Please feel free to reopen this is the issue persist, but I believe it should be fixed now.

**Comment by oliveiracwb** [comment]
I wanted to let you know that the issue has been resolved, and everything is working perfectly now. Thank you so much for your prompt attention and support!
