### ISSUE TITLE
Error running query: Initial weights length does not match number of graph nodes

### ISSUE THREAD

**Issue by NISH1001** [circlemind-ai/fast-graphrag#30]
Hi,

Thank you for implementing faster graph RAG. Appreciate it. I am encountering a problem during the query.

---

The problem arises in query time, throwing error in [`score_nodes(...)`](https://github.com/circlemind-ai/fast-graphrag/blob/dea484f1a513240095d5d027f11edb5c101a57f6/fast_graphrag/_storage/_gdb_igraph.py#L154) . Here's the detail:

I am trying to index around 260k docs. These docs are relatively small (most are single paragraphs).

I have been indexing these for 6+ hours now. I can resume it from the saved directory. However, after loading from the directory/last checkpoint, when I try to query, it throws me this error. Looking around with debugging, it stems from the score_nodes, where the initial_weights don't match the desired node count.

```python
if initial_weights is not None:
    if initial_weights.shape[1] != num_nodes:
        raise ValueError(f"Initial weights length ({initial_weights.shape[1]}) does not match number of graph nodes ({num_nodes}).")
```

Does the resume functionality have a bug?

---

To give more detail:
I did a wrapper around the insertion outside in my code, so that I could chunk 260k docs in batches and build the graph
```python
def chunks(lst: List[str], n: int):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]

@retry(stop=stop_after_attempt(3), wait=wait_fixed(1))
def insert_with_retry(grag, batch: List[str]):
    grag.insert(batch)

def insert_graphrag_batched(grag, docs: List[str], batch_size: int = 1000):
    for batch in chunks(docs, batch_size):
        insert_with_retry(grag, batch)
    return grag
```

- At first I was using batch size of 100. `grag = insert_graphrag_batched(grag, DOCS, batch_size=100)`
- Then I stopped the kernel and restarted the indexing with batch size of 2000. `grag = insert_graphrag_batched(grag, DOCS, batch_size=2000)`

Technically since the indexing resumed normally without throwing errors, I feel this is not the issue.

The issue happens when I run `grag.query(...)`

The original error happens to be with running pagerank with this mismatch in length. Is there anything I can do (without re-running the whole indexing from scratch as that will require more time and $$$$).
```
InternalError: Error at src/centrality/prpack.cpp:51: Invalid length of reset vector when calculating personalized PageRank scores. -- Invalid value
```

---

cc: @liukidar

Thanks

**Comment by liukidar** [comment]
Hey, it looks like for some reason the number of entities in the vector storage and the number of nodes in the graph are different (which should not happen). First of all, at the moment the number of entities in the vector storage is capped at 1 milion, maybe that's the problem, but let's see. I would start by checking of how much the two number differ. The following code should work:
```python
async def _run():
            await grag.state_manager.query_start()
            nodes = await grag.state_manager.get_num_entities()  # number of nodes in the graph
            embeddings = grag.state_manager.entity_storage._index.get_current_count()
            await grag.state_manager.query_done()
            return nodes, embeddings

        n_nodes, n_embeddings = get_event_loop().run_until_complete(_run())
        print(f"Graph has {n_nodes} nodes and {n_embeddings} embeddings.")
```

**Comment by NISH1001** [comment]
@liukidar Thanks for the prompt reply.

Right now the difference is in 100ish order:
```
Graph has 315312 nodes and 315162 embeddings.
```

While I write this, the indexing is still running. It's weird how the nodes and entities don't match because the indexing is working perfectly if I interrupt and resume from last checkpoint. Could you help point in a right direction how I can resolve this so that all my indexing time isn't wasted. I can load the graph separately but that's all about it I can do. the `query(...)` still throws this error. Thanks.

**Comment by liukidar** [comment]
> @liukidar Thanks for the prompt reply.
> 
> Right now the difference is in 100ish order:
> 
> ```
> Graph has 315312 nodes and 315162 embeddings.
> ```
> 
> While I write this, the indexing is still running. It's weird how the nodes and entities don't match because the indexing is working perfectly if I interrupt and resume from last checkpoint. Could you help point in a right direction how I can resolve this so that all my indexing time isn't wasted. I can load the graph separately but that's all about it I can do. the `query(...)` still throws this error. Thanks.

No worries, it should be quite easy to solve your problem. The embeddings are computed from the graph nodes, so we simply need to identify which ones are missing and insert them again. If you reach out on discord I'd be happy to work out with you a specific solution.

**Comment by liukidar** [comment]
@NISH1001 Hey, I'm still very happy to jump on a call and help you out! Otherwise I'll close this issue as I believe the bug behind it has been fixed.

**Comment by NISH1001** [comment]
Hi Thanks, For now let's close this issue. Thanks for your work. Appreciate it.
