### ISSUE TITLE
It is not able to answer general questions

### ISSUE THREAD

**Issue by vanetreg** [circlemind-ai/fast-graphrag#33]
**Describe the bug**
I tested the example snippet available on README.md with my own questions and I got 
_"Sorry, I'm not able to provide an answer to that question."_
responses.

My questions were general, **not entity focused**, like:
- What is the story about?
- Pls. summarize me the story!
- Where does the story happen mainly?

**To Reproduce**
Try to test it with such questions.

**Expected behavior**
it answers correctly.

I think the workflow should be modified to be able to handle such general questions.

**Comment by 9prodhi** [comment]
For generic queries that are not entity-focused, such as:

- *What is the story about?*
- *Please summarize the story for me!*
- *Where does the story mainly happen?*

In `fast_graphrag/_graphrag.py`, the following code attempts to extract entities from the query:

```python
# Extract entities from query
extracted_entities = await self.information_extraction_service.extract_entities_from_query(
    llm=self.llm_service, query=query, prompt_kwargs={}
)
```


However, in these cases, ```extracted_entities``` returns:

```json
{"entities": [], "n": 0}
```

This leads to an issue in the ```get_context``` function within ```fast_graphrag/_services/_state_manager.py```, where the function returns None:

```python
async def get_context(
    self, query: str, entities: Iterable[TEntity]
) -> Optional[TContext[TEntity, TRelation, THash, TChunk]]:
    if self.entity_storage.size == 0:
        return None

    try:
        entity_names = [entity.name for entity in entities]
        if len(entity_names) == 0:
            return None
```
As a result, we receive the response:

    "Sorry, I'm not able to provide an answer to that question."
    
 
For generic questions like these, we should consider the entire graph as the context and filtering key entities and relations based on specific filtering criteria.

@liukidar What are your thoughts on how we could address this?

**Comment by liukidar** [comment]
@9prodhi You are totally right here. The second if should definitely not be there now that we have hybrid querying (we also select nodes based on query similarity like in graphrag/lightrag). Since you spotted this, I'd be happy if you issued a pull request that skips the embedding step for the entities if there are none and only uses the query in that case. I can also do that if you prefer :)

**Comment by liukidar** [comment]
More in general, @vanetreg, we are looking at taking some inspiration from lightrag and introducing an idea of "generic concepts" that can be useful to connect far away nodes and hopefully help in answering more general quesitons (also right now the llm prompt may not be really tuned for that kind of questions, but we have to try and see).

**Comment by 9prodhi** [comment]
@liukidar Thanks for the prompt response! I’ll take a look and implement some logic similar to MS graphrag/lightrag.

**Comment by liukidar** [comment]
> @liukidar Thanks for the prompt response! I’ll take a look and implement some logic similar to MS graphrag/lightrag.

Ahah, no need to do that (but I'm very happy to chat about it if you're keen to) :) I simply thought that it would have been nice for you to contribute to the repo to change the couple of lines of code of that wrong `if`, but no worries if it's too bothering, I can do that.
Basically the if should be around
```python
vdb_entity_scores_by_name = await self._score_entities_by_vectordb(
                query_embeddings=query_embeddings[:-1], top_k=1
            )
```
instead of returning None.

**Comment by vanetreg** [comment]
I think an agent can decide if the question / query is stored entity related or not. If so use graph retriever with LLM A, if not stored entity related, use LLM B with hybrid retriever (eg. BM25 + vector)

**Comment by liukidar** [comment]
We kinda do this already, however there was an if preventing the llm to try to answer if the question contained no relevant entities.

**Comment by liukidar** [comment]
Any feedback on this? I believe this is now fixed.

**Comment by vanetreg** [comment]
> Any feedback on this? I believe this is now fixed.

I tested it with 2 of the mentioned generic questions and the response seemed to be OK. ( I don't know the book )
