### ISSUE TITLE
GraphRAG object is not JSON serializable

### ISSUE THREAD

**Issue by sailorjs0804** [circlemind-ai/fast-graphrag#39]
**Describe the bug**
I want to store Object of type GraphRAG into Manager().dict(), but itis not JSON serializable object

**To Reproduce**
json.dumps(GraphRAG, intent=2)

**Expected behavior**
I want to serialize it and deserialize

**Screenshots**
![image](https://github.com/user-attachments/assets/747881fb-355a-424c-a2e5-1eaf6e084755)

**Additional context**
No other information

**Comment by sailorjs0804** [comment]
When I use pickle to serializable GraphRAG, it show errors like this:
![image](https://github.com/user-attachments/assets/638eba97-f542-4091-a130-d3c470eff918)

**Comment by sailorjs0804** [comment]
When I use dill to serialize, it shows errors like this:
![image](https://github.com/user-attachments/assets/ec6f94ee-593e-4e6c-b6f4-6e7fa99ea6c4)

**Comment by liukidar** [comment]
Hi, unfortunately it is not serialisable as it contains to many non serialisable dependencies. What is the end goal you're trying to achieve?

**Comment by sailorjs0804** [comment]
Low latency is critical to our scenery，We try to reduce GraphRAG loading time，so we plan to load same graph just one time in memory which can be used many times and we
control GraphRAG gc. In multiprocess，we can not pass same GraphRAG object because it can not serialize

**Comment by liukidar** [comment]
Hello. I'm not sure what you mean with the multiprocess part, but you can keep a graphrag object in memory and create responses to multiple queries (also asynchronously). An example on how to achieve that for a batch of queries is the following:
```
from fast_graphrag._utils import get_event_loop

grag = GraphRAG(
    working_dir=working_dir,
    domain=DOMAIN,
    example_queries="\n".join(QUERIES),
    entity_types=ENTITY_TYPES,
)

async def _run(queries: List[str]):
    await grag.state_manager.query_start()
    answers = [
        await a
        for a in tqdm(asyncio.as_completed([grag.async_query(query) for query in queries]), total=len(queries))
    ]
    await grag.state_manager.query_done()
    return answers

answers = get_event_loop().run_until_complete(_run(queries))
```

**Comment by sailorjs0804** [comment]
Thanks, I will have a try
