### ISSUE TITLE
Kind question from nano-graphrag

### ISSUE THREAD

**Issue by gusye1234** [circlemind-ai/fast-graphrag#6]
Hi, really cool and solid project!

I'm the author of nano-graphrag and looking for the project's that nano-graphrag helped in some degree, and add those project to here: https://github.com/gusye1234/nano-graphrag?tab=readme-ov-file#projects-that-used-nano-graphrag
 to make people trust nano-graphrag. 

Do you consider nano-graphrag help this project in some way? It will be my honor to list this cool project in the readme of nano-grapgrag!

Thanks❤️

**Comment by liukidar** [comment]
Yes, of course, feel free to mention us — that would be amazing! We drew inspiration from both nano-graphrag and HippoRAG (https://arxiv.org/abs/2405.14831). Our goal is to take these research-oriented projects and develop production-ready tools that are easy to tune and integrate.
