### ISSUE TITLE
Run Fast-GraphRAG locally

### ISSUE THREAD

**Issue by Z-ZHHH** [circlemind-ai/fast-graphrag#8]
Thanks for sharing the work. How to Run Fast-GraphRAG Locally with FastChat/Ollama Models

**Comment by Z-ZHHH** [comment]
Thank you for your response. I'd like to clarify the setup process for Fast-GraphRAG.

To run GraphRAG with Fastchat, the setup process involves two main steps:

1. Initialize the environment by running:
`python -m graphrag.index --init --root ./ragtest`

2. Modify the setting.yaml file in ./ragtest to configure:
    * The `api_base` 
    * The `model_name`

After these configurations, GraphRAG can be run with my local model.

Could you confirm if Fast-GraphRAG follows this same setup procedure, or are there additional/different steps required?

**Comment by liukidar** [comment]
I'm not very familiar with FastChat, but according to here (https://github.com/lm-sys/FastChat/blob/main/docs/openai_api.md), they support the OpenAI API format so it should be compatible. In particular, please try the following configuration:

```python

from fast_graphrag._llm import OllamaAIEmbeddingService, OllamaAILLMService

grag = GraphRAG(
    working_dir=working_dir,
    domain=DOMAIN,
    example_queries="\n".join(QUERIES),
    entity_types=ENTITY_TYPES,
    config=GraphRAG.Config(
        llm_service=OllamaAILLMService(model="your-llm-model", base_url="api_base"),
        embedding_service=OllamaAIEmbeddingService(model="your-embedding-model", base_url="api_base"),
    ),
)
```
where, if my understanding is correct, `base_url` corresponds to the api entry point which for you is `api_base` and `model` is your `model_name`. Let me know if this works, otherwise I'm happy to get into the details.

**Comment by yang605222** [comment]
I want use other LLM,not gpt-4o,how can I do?

**Comment by liukidar** [comment]
> I want use other LLM,not gpt-4o,how can I do?

Hello! Do you want to use other open ai LLMs, or local ones?

**Comment by yang605222** [comment]
Thanks for your reply.
Yeah,I want use use other open ai LLMs.Such as   client = OpenAI(
                        api_key="sk-xxx",
                        base_url="https://api.deepseek.com",
                    ) 
And how  should modify the code?

**Comment by YeKelvin** [comment]
Error during information extraction from document: Instructor does not support multiple tool calls, use List[Model] instead

<img width="1048" alt="image" src="https://github.com/user-attachments/assets/b146d84f-7f82-4cf4-a57d-6e5dd5a88688">

https://python.useinstructor.com/concepts/parallel/?h=parallel#understanding-parallel-function-calling

**Comment by Dormiveglia-elf** [comment]
> Thanks for your reply. Yeah,I want use use other open ai LLMs.Such as client = OpenAI( api_key="sk-xxx", base_url="https://api.deepseek.com", ) And how should I modify the code?

Same question

**Comment by liukidar** [comment]
> Thanks for your reply. Yeah,I want use use other open ai LLMs.Such as client = OpenAI( api_key="sk-xxx", base_url="https://api.deepseek.com", ) And how should I modify the code?

Hello, deepseek APIs seem to be compatible with OpenAI APIs. Please check `examples/custom_llm.py` tp see how to configure GraphRAG to use your service.

**Comment by liukidar** [comment]
> Error during information extraction from document: Instructor does not support multiple tool calls, use List[Model] instead
> 
> <img alt="image" width="1048" src="https://private-user-images.githubusercontent.com/16164014/384885023-b146d84f-7f82-4cf4-a57d-6e5dd5a88688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NjY0NTYsIm5iZiI6MTczMTQ2NjE1NiwicGF0aCI6Ii8xNjE2NDAxNC8zODQ4ODUwMjMtYjE0NmQ4NGYtN2Y4Mi00Y2Y0LWE1N2QtNmU1ZGQ1YTg4Njg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDAyNDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMDViMGVhZDczNDBhNmI4NmRiM2NmMDZhYjVjNDExYTQ4ODBmMDY2MjM1MTVlODNkOTE0N2I2YzY0OTQ1ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ogfRypgGAARlMFSPL0HbUO_wQjWoh857EeQuoah2fNU">
> https://python.useinstructor.com/concepts/parallel/?h=parallel#understanding-parallel-function-calling

Hey, thanks for highlighting this. I'm unsure what's the cause beyond this error message. Could you please open a new issue and maybe provide a minimum working example that generates this issue?

**Comment by liukidar** [comment]
Let's move this to https://github.com/circlemind-ai/fast-graphrag/issues/20
