### ISSUE TITLE
pip dependencies conflict

### ISSUE THREAD

**Issue by Dormiveglia-elf** [circlemind-ai/fast-graphrag#9]
**Describe the bug**
When I first execute pip install fast-graphrag:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
graspologic 3.4.1 requires scipy==1.12.0, but you have scipy 1.14.1 which is incompatible.
gensim 4.3.3 requires scipy<1.14.0,>=1.7.0, but you have scipy 1.14.1 which is incompatible.

if I pip install scipy==1.12.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fast-graphrag 0.0.1.post0 requires scipy<2.0.0,>=1.14.1, but you have scipy 1.12.0 which is incompatible.

I think it is impossible to solve the conflict now.
**To Reproduce**
1. pip install fast-graphrag
2. pip install scipy==1.12.0
3. pip check

**Expected behavior**
No conflict

**Screenshots**

**Additional context**

**Comment by liukidar** [comment]
Hello! I have tried running it with scipy==1.12.0 and nothing seems to break, so you should be good by just running `pip install scipy==1.12.0` and then using the code as normally. (However, not that those packages you plan to use are not officially supported).

**Comment by Dormiveglia-elf** [comment]
> Hello! I have tried running it with scipy==1.12.0 and nothing seems to break, so you should be good by just running `pip install scipy==1.12.0` and then using the code as normally. (However, note that those packages you plan to use are not officially supported).

I just clone your repo from github, still get the error below
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fast-graphrag 0.0.1.post0 requires scipy<2.0.0,>=1.14.1, but you have scipy 1.12.0 which is incompatible.
Successfully installed scipy-1.12.0

**Comment by liukidar** [comment]
> > Hello! I have tried running it with scipy==1.12.0 and nothing seems to break, so you should be good by just running `pip install scipy==1.12.0` and then using the code as normally. (However, note that those packages you plan to use are not officially supported).
> 
> I just clone your repo from github, still get the error below ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. fast-graphrag 0.0.1.post0 requires scipy<2.0.0,>=1.14.1, but you have scipy 1.12.0 which is incompatible. Successfully installed scipy-1.12.0

It looks like in the environment where you are trying to install the library you have already some other packages that require scipy 1.12.0 which is not (officialy) compatible with fast-graphrag. To solve this issue you should either remove those packages before installing fast-graphrag or install it in a different virtual environment.

Let me know if this solves your issue.
